[project]
name = "thunderskin"
version = "0.4.0"
description = "Process JSON data of Cultist Simulator."
readme = "README.md"
requires-python = ">=3.13"
license = "MIT"
license-files = ["LICEN[CS]E*"]
authors = [{ name = "SOgz12Z3Ce", email = "sogz12z3ce@proton.me" }]
classifiers = [
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3",
]
dependencies = [
  "rich>=15.0.0",
]

[project.urls]
Homepage = "https://github.com/SOgz12Z3Ce/thunderskin"
Issues = "https://github.com/SOgz12Z3Ce/thunderskin/issues"

[project.scripts]
thunderskin = "thunderskin:main"

[dependency-groups]
dev = [
  "ruff>=0.16.0",
  "ty>=0.0.65",
]

[build-system]
requires = ["uv_build>=0.11.32,<0.12.0"]
build-backend = "uv_build"

[tool.ruff.lint]
select = ["ALL"]
ignore = [
  "D203",
  "D213",
]
